### ISSUE TITLE
Logo Design for ToxicBot

### ISSUE THREAD

**Issue by Sid200026** [Sid200026/ToxicBot#11]
You'll be responsible for designing a logo for ToxicBot. The logo shouldn't have any copyright infringements.

- The logo should be transparent
- Logo should be added in the `public` folder in the root directory.
- The logo should related to the following domains
     - Discord
     - Toxic

**Comment by M4yankChoudhary** [comment]
I can help in making the logo.

**Comment by Sid200026** [comment]
Go ahead
