### ISSUE TITLE
Database Support to retain information about user toxic messages

### ISSUE THREAD

**Issue by Sid200026** [Sid200026/ToxicBot#6]
Currently the bot does not maintain any information regarding the amount of toxic messages sent by an user. This makes it impossible to kick out users. Add database support to the bot to retain the number of toxic messages sent by each user along with the server information

**Database Schema**

| Server_ID | User_ID | ToxicCount |
|-----------|---------|------------|

Other information maybe added based on the requirements

**Task**

- Added database support to the application
- The database must be either PostgreSQL or MongoDB
- Whenever a message is classified as toxic, store its information in the database
- Update the README file accordingly

**Comment by otacon94** [comment]
Do you still need help with these?

**Comment by Sid200026** [comment]
@otacon94 I have mostly completed this module. You could go ahead and work on any other issue or raise your own issue/feature and then work on it.
