### ISSUE TITLE
Interaction with members in the DMs

### ISSUE THREAD

**Issue by Sid200026** [Sid200026/ToxicBot#7]
Currently the users can interact with the bot in their private DMs using `/info` only. Make the bot more interactive by adding the following new command

- `/help` : List of commands and their description
- `/report` : Should send this link https://github.com/Sid200026/ToxicBot/issues

**Comment by otacon94** [comment]
i can do this

**Comment by Sid200026** [comment]
Cool. I'll assign it to you

**Comment by otacon94** [comment]
@Sid200026 should be ok now :D please check :D
